/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esiii_strategy;

import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JPanel;


/**
 *
 * @author mayarasantos
 */
public class FormCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }
    
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        FormCliente = new javax.swing.JInternalFrame();
        nome = new javax.swing.JTextField();
        label_Nome = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        label_CPF = new javax.swing.JLabel();
        label_rua = new javax.swing.JLabel();
        label_Bairro = new javax.swing.JLabel();
        label_Num = new javax.swing.JLabel();
        label_Estado = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        bairro = new javax.swing.JTextField();
        estado = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        label_Cidade = new javax.swing.JLabel();
        label_Titulo = new javax.swing.JLabel();
        salvar = new javax.swing.JButton();
        Parentesco1 = new javax.swing.JLabel();
        parestenco1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        NomeDependente1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Parentesco2 = new javax.swing.JLabel();
        parestenco2 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        NomeDependente2 = new javax.swing.JTextField();
        Label_CEP = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();

        FormCliente.setVisible(true);

        javax.swing.GroupLayout FormClienteLayout = new javax.swing.GroupLayout(FormCliente.getContentPane());
        FormCliente.getContentPane().setLayout(FormClienteLayout);
        FormClienteLayout.setHorizontalGroup(
            FormClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FormClienteLayout.setVerticalGroup(
            FormClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, FormCliente, org.jdesktop.beansbinding.ObjectProperty.create(), this, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        label_Nome.setText("Nome");

        cpf.setToolTipText("");
        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        label_CPF.setText("CPF");

        label_rua.setText("Rua");
        label_rua.setToolTipText("");

        label_Bairro.setText("Bairro");

        label_Num.setText("Nº");

        label_Estado.setText("Estado");

        bairro.setToolTipText("");

        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });

        label_Cidade.setText("Cidade");

        label_Titulo.setText("Cadastro de Cliente");

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        Parentesco1.setText("Parentesco");

        parestenco1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não tem dependente", "Filho(a)", "Cônjuge", "Mãe", "Pai" }));
        parestenco1.setSelectedIndex(-1);
        parestenco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parestenco1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Dependentes");

        jLabel2.setText("Nome:");

        jLabel3.setText("Nome:");

        Parentesco2.setText("Parentesco");

        parestenco2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não tem dependente", "Filho(a)", "Cônjuge", "Mãe", "Pai" }));
        parestenco2.setSelectedIndex(-1);
        parestenco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parestenco2ActionPerformed(evt);
            }
        });

        Label_CEP.setText("CEP");

        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(label_Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(salvar)))
                .addContainerGap(354, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_rua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_Num)
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_CPF)
                                .addGap(18, 18, 18)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NomeDependente2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Parentesco2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(parestenco2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Parentesco1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(parestenco1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(254, 254, 254))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NomeDependente1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Label_CEP)
                                .addGap(18, 18, 18)
                                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_Estado)
                                    .addComponent(label_Cidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estado)
                                    .addComponent(cidade)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(label_Bairro)
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rua)
                                        .addGap(48, 48, 48)
                                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bairro, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Titulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_CPF))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_rua)
                    .addComponent(label_Num)
                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Bairro)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CEP)
                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Estado)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Cidade))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeDependente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Parentesco1)
                    .addComponent(parestenco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NomeDependente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Parentesco2)
                    .addComponent(parestenco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(salvar)
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here: 

    }//GEN-LAST:event_salvarActionPerformed

    private void parestenco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parestenco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parestenco1ActionPerformed

    private void parestenco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parestenco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parestenco2ActionPerformed

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame FormCliente;
    private javax.swing.JLabel Label_CEP;
    private javax.swing.JTextField NomeDependente1;
    private javax.swing.JTextField NomeDependente2;
    private javax.swing.JLabel Parentesco1;
    private javax.swing.JLabel Parentesco2;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_Bairro;
    private javax.swing.JLabel label_CPF;
    private javax.swing.JLabel label_Cidade;
    private javax.swing.JLabel label_Estado;
    private javax.swing.JLabel label_Nome;
    private javax.swing.JLabel label_Num;
    private javax.swing.JLabel label_Titulo;
    private javax.swing.JLabel label_rua;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JComboBox<String> parestenco1;
    private javax.swing.JComboBox<String> parestenco2;
    private javax.swing.JTextField rua;
    private javax.swing.JButton salvar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public JTextField getBairro() {
        return bairro;
    }

    public void setBairro(JTextField bairro) {
        this.bairro = bairro;
    }

    public String getCidade() {
        return cidade.getText();
    }

    public void setCidade(JTextField cidade) {
        this.cidade = cidade;
    }

    public String getCpf() {
        return cpf.getText();
    }

    public void setCpf(JTextField cpf) {
        this.cpf = cpf;
    }

    public String getEstado() {
        return estado.getText();
    }

    public void setEstado(JTextField estado) {
        this.estado = estado;
    }

    public String getRua() {
        return rua.getText();
    }

    public void setRua(JTextField rua) {
        this.rua = rua;
    }

    public JLabel getLabel_Bairro() {
        return label_Bairro;
    }

    public void setLabel_Bairro(JLabel label_Bairro) {
        this.label_Bairro = label_Bairro;
    }

    public int getCep() {
        return Integer.parseInt(cep.getText());
    }

    public void setCep(JTextField cep) {
        this.cep = cep;
    }

    public JLabel getLabel_CPF() {
        return label_CPF;
    }

    public void setLabel_CPF(JLabel label_CPF) {
        this.label_CPF = label_CPF;
    }

    public JLabel getLabel_Cidade() {
        return label_Cidade;
    }

    public void setLabel_Cidade(JLabel label_Cidade) {
        this.label_Cidade = label_Cidade;
    }

    public JLabel getLabel_Estado() {
        return label_Estado;
    }

    public void setLabel_Estado(JLabel label_Estado) {
        this.label_Estado = label_Estado;
    }

    public JLabel getLabel_Nome() {
        return label_Nome;
    }

    public void setLabel_Nome(JLabel label_Nome) {
        this.label_Nome = label_Nome;
    }

    public JLabel getLabel_Num() {
        return label_Num;
    }

    public void setLabel_Num(JLabel label_Num) {
        this.label_Num = label_Num;
    }

    public JLabel getLabel_Titulo() {
        return label_Titulo;
    }

    public void setLabel_Titulo(JLabel label_Titulo) {
        this.label_Titulo = label_Titulo;
    }

    public JLabel getLabel_rua() {
        return label_rua;
    }

    public void setLabel_rua(JLabel label_rua) {
        this.label_rua = label_rua;
    }

    public String getNome() {
        return nome.getText();    
    }

    public void setNome(JTextField nome) {
        this.nome = nome;
    }

    public int getNumero() {
        return Integer.parseInt(numero.getText());
    }

    public void setNumero(JTextField numero) {
        this.numero = numero;
    }

    public String getNomeDependente1() {
        return NomeDependente1.getText();
    }

    public void setNomeDependente1(javax.swing.JTextField NomeDependente1) {
        this.NomeDependente1 = NomeDependente1;
    }

    public String getNomeDependente2() {
        return NomeDependente2.getText();
    }

    public void setNomeDependente2(javax.swing.JTextField NomeDependente2) {
        this.NomeDependente2 = NomeDependente2;
    }

    public String getParestenco1() {
        return parestenco1.getSelectedItem().toString();
    }

    public void setParestenco1(javax.swing.JComboBox<String> parestenco1) {
        this.parestenco1 = parestenco1;
    }

    public String getParestenco2() {
        return parestenco2.getSelectedItem().toString();
    }

    public void setParestenco2(javax.swing.JComboBox<String> parestenco2) {
        this.parestenco2 = parestenco2;
    }
    
}
